### ISSUE TITLE
How to get the raw feature of paper100M?

### ISSUE THREAD

**Issue by classicsong** [amzn/pecos#102]
## Description
After downloading ogbn-papers100M.tar.gz, I can only get X.all.xrt-emb.npy and X.all.xrt-emb.sgc.pt. There is no Xall.txt

## References
- list reference and related literature
- list known implementations

**Comment by elichienxD** [comment]
Hi @classicsong ,

It can be downloaded at OGB's official github repo (at the end of the page):
https://github.com/snap-stanford/ogb/tree/master/examples/nodeproppred/papers100M

Best,
Eli
