### ISSUE TITLE
Minor bug in XR-Transformer run.sh

### ISSUE THREAD

**Issue by nilesh2797** [amzn/pecos#105]
https://github.com/amzn/pecos/blob/b01b97afab3de5090c5c5fb8df66854797ef73a9/examples/xr-transformer-neurips21/run.sh#L2

this line should be `data_dir="./xmc-base/${data}/" `?

**Comment by jiong-zhang** [comment]
Thanks for the catch. This is fixed in https://github.com/amzn/pecos/pull/106
