### ISSUE TITLE
Switch back to X-Transformer

### ISSUE THREAD

**Issue by xiayandi** [amzn/pecos#116]
## Description
I notice that X-Transformer entry point now is also used by XR-Transformer. Is there a option to choose/decide with algorithm is being used under the hood?

**Comment by jiong-zhang** [comment]
Hi @xiayandi, the current entry point is only designed for XR-Transformer. If you want X-Transformer, you can use this [repo](https://github.com/OctoberChang/X-Transformer).

**Comment by xiayandi** [comment]
Thanks!
