### ISSUE TITLE
Format of yt label

### ISSUE THREAD

**Issue by arita37** [amzn/pecos#122]
Hello,

hope you are fine, have 2 questions about the format

Question 1
Have one question about optimal format for label Yt.
Is it preferable to have Yt as:

(A)   OneHot encoded with only one  1  per row.
(B)    Mutiple OneHot encode  with mutiple 1 per rows  (as this is the case for Xt).

When the prediction is done, it seems only outputing only  one 1 per row.

Question 2:

   Is there any constraint by having Xt as having a mix of dense input  and sparse input
   instead of sparse input only ?

**Comment by jiong-zhang** [comment]
Hi @arita37, generally speaking the label matrix could have arbitrary number of positive per instance. For the combined dense and sparse input, you can concatenate the dense and sparse vectors and view the result as another sparse input ([example](https://github.com/amzn/pecos/blob/mainline/pecos/xmc/xtransformer/matcher.py#L895)).

**Comment by arita37** [comment]
Hello Zhang,

   Thanks for confirming.
    Incase of mutiple label y oer instance,
How the top-k results works.
   It seems generating only topk values per instance.

Shouldn’t be
     Topk x Nlabel per instance (?)

ie Suppose the labels can be correlated (ie hiearchy of label per instance).

Thx

**Comment by jiong-zhang** [comment]
What is N in your question?
For each instance, the prediction will generate top-k out of all the labels in the output space.
For more information, you can refer to section 2.5 of our [paper](https://arxiv.org/pdf/2010.05878.pdf).

**Comment by arita37** [comment]
Hello Zhang,
Thx.

Suppose we have
  Ylabel :  5000 samples x 1000 cols

and each instance has 10 labels :
     Count_one(Ylabel[i. :]) == 10
(In the training phase).

In the inference
   Suppose Topk=7

Currently, it outputs 7 “one”
 per  predicted instance…..

Shouldn’t be
     7x10  “ones” per predicted instance

Thanks

**Comment by arita37** [comment]
To add on this topic:

Suppose this is related to the
independance of each individuaul ylabel
 
For one sample,
   Count_One(yi) = 11
   If all the individual labels are independant
        Topk prediction returns topk values
         (ie one individual label per sample


    If all the individual labels have an “forced” 
    structure  (ie hiearchy in the individual labels):
         Topk prediction should “keep” the structure
        in the output :
               return  (topk x 11 ) per sample


Think “imposing” structure may not be straightforward in current version of pcos.

Thanks

**Comment by jiong-zhang** [comment]
When asking the model to predict `only_topk=7`, you should expect the mode to output 7 labels for each input instance (instead of 70).

**Comment by arita37** [comment]
It means that during training
we can provide more 
than 7 labels  per training sample ?

Thanks
