### ISSUE TITLE
Add Support for User Supplied Negatives to Text2Text App

### ISSUE THREAD

**Issue by simonhughes22** [amzn/pecos#124]
It appears that the regular PECOS library allows you to pass in user supplied negative examples as additional training data. However this does not appear to be exposed in the Text2Text app as far as I can tell from reading the code. Please can you add support for this functionality to the app as well so i can augment a model with additional negative examples?

**Comment by jiong-zhang** [comment]
Hi @simonhughes22 , the `text2text` module is providing wrapper around `xlinear` with minimal functionalities, we currently have no plan to expose this function to text2text. If you would like to use the `usn` feature, it would be as easy to directly use `xlinear`.
