### ISSUE TITLE
Add the Ability to Extract the Cluster Label Tree from the Model

### ISSUE THREAD

**Issue by simonhughes22** [amzn/pecos#125]
I cannot see a way to get the model to easily output the full label tree structure. It is stored internally in a series of matrices but it's non trivial to reverse engineer the label tree from that. I'd like to experiment with using the label tree for various tasks, such as training a separate model (so just using PECOS for clustering) or using the clusters themselves as a set of unsupervised features for input to a model. Can you add a feature to allow extraction of the label tree in some easily digestible format?

**Comment by jiong-zhang** [comment]
Hi @simonhughes22 , you can get the cluster chain rather simply with existing API. For example:
```
from pecos.xmc.xlinear import XLinearModel
from pecos.utils.cluster_util import ClusterChain
model = XLinearModel.load("where/you/store/the/model")
cluster_chain = ClusterChain([m.C for m in model.model.model_chain])
```

**Comment by simonhughes22** [comment]
@jiong-zhang can you explain how to interpret the output of that chain? How does it map to the labels provided?

**Comment by jiong-zhang** [comment]
The core part of that chain is a list of sparse matrices and `len(cluster_chain)` is the depth of the tree.

`cluster_chain[t][i,j]=1` means that the i-th node on level (t+1) is a child of j-th node on level t.

For more details please see section 2.1.2 of our [tech doc](https://arxiv.org/pdf/2010.05878.pdf).

**Comment by pedroruas18** [comment]
Following the question by @simonhughes22, would it be possible to provide a cluster chain built externally and train the model with it?
