### ISSUE TITLE
How to use GIANT-XRT model to pre-train my own data

### ISSUE THREAD

**Issue by Y77GitHub** [amzn/pecos#126]
## Description
(I want to get embedding of each node by using GIANT-XRT model rather than a Bert model,which shows more effecient in the paper  ,and also I have the edges between nodes.I emailed to the author who helped me a lot,I'm very appreciate it.Following are some steps)
- The first step is to prepare the graph, edge_index: This is a 2*|E| tensor which include the information of edges of the underlying graph. For example, edge_index[:,0] will be the first edge and edge_index[0,0], edge_index[1,0] are the starting and ending node id of that edge respectively. Once your are done, modify line 29-32 accordingly.
- Next I prepare the raw text of each node. It is a text file and line "n" contain the related raw text of node of id "n". And I put it in the path of "args.raw-text-path".
- I have been run the complete training for ogbn-arxiv successfully,got 5 files"Y.trn.npz，Y.all.npz，X.trn.txt，X.all.tfidf.npz，X.trn.tfidf.npz",but I still confused because they are not my target,seems the file "X.all.xrt-emb.npy" may be what I want,but it was generated from XR-Transformer,should I run the XR-Transformer?

**Comment by elichienxD** [comment]
Hi @Y77GitHub,

The file ``X.all.xrt-emb.npy`` is exactly the resulting node features that you can use for downsteam tasks. Note that GIANT is the framework of using graph information to help extracting better node features. XR-Transformer is the SOTA solution for the extreme multilabel classification, which is used in our GIANT framework. Together it is called GIANT-XRT in short. Please read our paper for more detail.

Best,
Eli
