### ISSUE TITLE
Does 'sigmoid' post-processor output predicted probability of labels?

### ISSUE THREAD

**Issue by theejung** [amzn/pecos#132]
Hi,

I recently run XRTransformer and XRLinear models to benchmark datasets and want to get the predicted probability P(Y_{i}=1|X) of labels. I believe both models are anyway OVA classifiers. Does it mean that I could simply apply a 'sigmoid' post-processor and understand this result as a predicted probability?

Thanks!

**Comment by jiong-zhang** [comment]
Hi @THEEJUNG, yes you can apply any post-processor function and map the ranking score to (0,1). However, whether the result can be directly interpreted as `p(y|x)` requires further study.
