### ISSUE TITLE
Papers100M model requirement

### ISSUE THREAD

**Issue by Rejuy** [amzn/pecos#133]
## Description
Hi! 
I'm doing some research with giant's code. I did make use of the embeddings of papers100M and arxiv, as well as the encoder model of the latter one, but it seemed that the encoder model of papers100M is not available right now. I wonder if you could publicize the model (maybe by offering the download method) ? That would be really helpful.
Thx!

**Comment by cenyk1230** [comment]
Same question

**Comment by OctoberChang** [comment]
The encoder for `ogbn-papers100M` dataset are available at [[link](https://archive.org/download/pecos-dataset/giant-xrt/ogbn-papers100M-v2.tar.gz)]. Closing this issue. Feel free to re-open if you encounter any additional issue.
