### ISSUE TITLE
Pecos on customized datasets

### ISSUE THREAD

**Issue by celsofranssa** [amzn/pecos#155]
Hello,

How to generate the instance-to-feature matrix in [SciPy CSR format](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) from raw texts?

**Comment by jiong-zhang** [comment]
Hi @celsofranssa, you can use `pecos.utils.featurization.text.preprocess` module to do that. Here is the [README](https://github.com/amzn/pecos/blob/mainline/pecos/utils/featurization/text/README.md)

**Comment by celsofranssa** [comment]
Great @jiong-zhang,

However, some questions remain:

1. Is there documentation about the same preprocessing using the `libpecos`? 
2. Where could someone find the `config.json` used to preprocess the benchmark datasets (eurlex-4k, wiki10-31k, amazoncat-13k, amazon-670k, wiki-500k, amazon-3m)? 
3. Where is the `max_feature` warned in the [README.md](https://github.com/amzn/pecos/tree/mainline/pecos/utils/featurization/text)?

**Comment by jiong-zhang** [comment]
* Using the PECOS provided preprocessing module is not required for PECOS model training, you can use any other method to construct the sparse feature, for example the vectorizer provided by [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html).
* To reproduce the result from our papers, please refer to the corresponding folders under `pecos/examples`. In particular for the results on public XMC benchmarks (eurlex-4k, wiki10-31k, amazoncat-13k, amazon-670k, wiki-500k, amazon-3m) we used features released by [AttentionXML](https://arxiv.org/pdf/1811.01727.pdf).
* You can use `python -c "from pecos.utils.featurization.text.vectorizers import Tfidf; print(Tfidf.train.__doc__)"` to see the full docstring for TFIDF training.

**Comment by celsofranssa** [comment]
@jiong-zhang, thank you.

**Comment by celsofranssa** [comment]
> Hi @celsofranssa, you can use `pecos.utils.featurization.text.preprocess` module to do that. Here is the [README](https://github.com/amzn/pecos/blob/mainline/pecos/utils/featurization/text/READM

> Hi @celsofranssa, you can use `pecos.utils.featurization.text.preprocess` module to do that. Here is the [README](https://github.com/amzn/pecos/blob/mainline/pecos/utils/featurization/text/README.md)

Is there an approach to archive the same result using Python directly (from libpecos pip package)?

**Comment by celsofranssa** [comment]
I found an approach using Python (from libpecos) in this [Kdd22 tutorial](https://github.com/amzn/pecos/blob/mainline/tutorials/kdd22/Session%204%20Utilities%20in%20PECOS.ipynb).
It would be interesting if this were documented in some way.
