### ISSUE TITLE
Decouple transformer vectorisers from sklearn-based ones

### ISSUE THREAD

**Issue by aCampello** [amzn/pecos#174]
## Description

Thank you very much for the nice repository. We are currently using XLinear, together with the multi-thread Tfidf vectoriser https://github.com/amzn/pecos/blob/18a1cc56edbabfe73c264200e981e22333998995/pecos/utils/featurization/text/vectorizers.py#L190-L194

It works as a charm. However, with the new transformer vectorisers, to use Tfidf I need to unnecessarily install all transformers/torch dependencies in my virtual environment. It would be good if the code was decoupled, so a user can just use Tfidf if needed, with a slim environment. In the past, I used to just install pecos with no dependencies, and then only install the specific dependencies for the specific modules - this is desirable for a production environment.

Proposal:

- That the pertained transformers in https://github.com/amzn/pecos/blob/18a1cc56edbabfe73c264200e981e22333998995/pecos/utils/featurization/text/vectorizers.py#L535-L537
Be moved to an independent file, say `pretrained_vectorizers.py`, alongside transformers and torch imports.

I'm happy to give this change a go, and contribute with a MR if the maintainers upvote it.

**Comment by aCampello** [comment]
Any thoughts by the maintainers? @OctoberChang @weiliw-amz ?

**Comment by OctoberChang** [comment]
@aCampello , as suggested, we decoupled the `vectorizer.py` to contain only tf-idf based vectorizers.
