### ISSUE TITLE
Examples with text

### ISSUE THREAD

**Issue by xyan326** [amzn/pecos#18]
## Description
Current example of X and Y only has numeric values. Could you please provide one example where X and Y are both text? Think the paper/method is targeted to solve such problems.

**Comment by OctoberChang** [comment]
Hi xyan326, thanks for your interest in PECOS.

As of the current version (i.e., PECOS release v0.1.0), we have a example usage of text2text pipeline with XR-Linear of PECOS. You can find the input/output format in this [[README](https://github.com/amzn/pecos/blob/mainline/pecos/apps/text2text/README.md)].

Please let us know if this resolve your issue, thanks.

**Comment by OctoberChang** [comment]
Closing this issue as there's no further comment.

**Comment by xyan326** [comment]
Thanks! Able to see the example for the text. Wondering if there is a direct code and data available in the GitHub to directly be used and get the model trained and model prediction and result. Thanks!

**Comment by Khalid-Usman** [comment]
Can i use the same model to text2Int ? 

E.g. I downloaded AmazonCat-13K dataset from [github](https://github.com/yourh/AttentionXML). How can i preprocess it to make npz file so that i can run XR-LINEAR model ?
