### ISSUE TITLE
XTransformer model can't be trained it always shows cuda out of memory

### ISSUE THREAD

**Issue by Pallavi3759** [amzn/pecos#202]
"CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.96 GiB total capacity; 1.40 GiB already allocated; 6.50 MiB free; 1.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF" it always shows after some time of excution.

**Comment by jiong-zhang** [comment]
You can use smaller batch size or smaller transformer encoder to save GPU memory. To train the models defined in `examples/xr-transformer-neurips21/` please use AWS `p3.16xlarge` instance or larger.

**Comment by Pallavi3759** [comment]
predictions are accurate but scores are very low , is there any way to increase the prediction scores

**Comment by jiong-zhang** [comment]
could you provide an example of `predictions are accurate but scores are very low`?

**Comment by Pallavi3759** [comment]
@jiong-zhang Input text: guard services
Predicted label: Psc_S206
Predicted score: 1.0
Predicted label: Naics_523110
Predicted score: 1.0
Predicted label: Naics_523120
Predicted score: 1.0
Predicted label: Naics_523910
Predicted score: 1.0
Predicted label: Naics_523991
Predicted score: 1.0
Predicted label: Naics_561612
Predicted score: 1.0
Predicted label: Naics_561613
Predicted score: 1.0
Predicted label: Naics_922150
Predicted score: 1.0
Predicted label: Naics_922190
Predicted score: 1.0
Predicted label: Naics_928110
Predicted score: 1.0
Predicted label: Naics_922120
Predicted score: 1.0
Predicted label: Psc_R430
Predicted score: 0.006939241662621498
Predicted label: Psc_V002
Predicted score: 0.004626440815627575
Predicted label: Naics_485111
Predicted score: 0.004626440815627575
Predicted label: Naics_488410
Predicted score: 0.004626440815627575
Predicted label: Naics_711212
Predicted score: 0.004626440815627575
Predicted label: Psc_U004
Predicted score: 0.004298868589103222
Predicted label: Psc_F110
Predicted score: 0.004275548737496138
Predicted label: Psc_U014
Predicted score: 0.003936069086194038 all of the codes are relatable to the input but only few of them having good prediction score

**Comment by Pallavi3759** [comment]
@jiong-zhang is there any parameter we can use for incremental learning in xtransformer customxtf
??

**Comment by jiong-zhang** [comment]
XR-Transformer supports training from you own pre-trained model with `init_model_dir`, for details please see our [tutorial](https://github.com/amzn/pecos/blob/mainline/tutorials/kdd22/Session%205%20eXtreme%20Multi-label%20Classification%20with%20XR-Transformer.ipynb).

As for the evaluation, please provide minimal example with PECOS evaluation functionalities so we can reproduce.

**Comment by Pallavi3759** [comment]
@jiong-zhang do we apply incremental learning in xtransformer for our custom data set???

**Comment by Pallavi3759** [comment]
@jiong-zhang we already use pretrained model in init_model_dir but can't recieve desired results we have huge data and our use case is  extreme multilable txt classification but prediction score are not desired is there any way to improve them for ex- milk and dairy for nd sd and ne.
0	milk and dairy items for customers in utah and nevada area.
0	milk and dairy products.
0	milk and dairy requirements.
0	milk and ice cream delivery servicesasheville durham fayetteville and salisbury nc.
0	milk and ice cream products. we have these kind of corpus and output label file but can't recieve desired score

**Comment by jiong-zhang** [comment]
We don't have built-in support for data sharding in single node training (if that's what you mean by 'incremental training'). If the result is not desirable you should maybe consider using some other libraries.
