### ISSUE TITLE
MasOS support

### ISSUE THREAD

**Issue by valeriomieuli** [amzn/pecos#205]
Hi all, this product is amazing!!

I was wondering is there is any trick to make it available for MacOS M1 systems.

Thank you :)

**Comment by weiliw-amz** [comment]
Thanks for contacting. Currently we do not have plans to support PECOS on MacOS.
If you would like to hack by yourself, please try installing all PECOS dependencies listed in the README.md and compiling PECOS from source. We could not provide a guide at this moment.
