### ISSUE TITLE
How to get "pseudo_pos_tfidf.json" of stage 2 in MACLR

### ISSUE THREAD

**Issue by geduo15** [amzn/pecos#206]
## Description
Hi, I found the paper shows that stage 2 is critical to the performance improving. But I have not found the related code which can generate top k labels via tf-idf feature. Can you share the related codes? (the code which can get "pseudo_pos_tfidf.json")

## References
https://github.com/amzn/pecos/blob/mainline/examples/MACLR/dataset.py#L146

**Comment by OctoberChang** [comment]
Given an input corpus `./input.txt` and the TF-IDF config file `./config.json`, 
we generate its TF-IDF feature matrix using PECOS's native featurization (https://github.com/amzn/pecos/tree/mainline/pecos/utils/featurization/text):
1. Building TF-IDF pre-processor and save to `./tfidf-model` folder:
```
python3 -m pecos.utils.featurization.text.preprocess build \
  --text-pos 0 \
  --input-text-path ./input.txt \
  --vectorizer-config-path ./config.json \
  --output-model-folder ./tfidf-model
```
For the `config.json`, we use the following hyper-parameters:
```
{
  "type": "tfidf",
  "kwargs": {
    "base_vect_configs": [
      {
        "ngram_range": [1, 1],
        "max_df_ratio": 0.98,
        "analyzer": "word"
      },
      {
        "ngram_range": [2, 2],
        "max_df_ratio": 0.98,
        "analyzer": "word"
      }
    ]
  }
}
```

2. Generate TF-IDF matrix and save to 
```
python3 -m pecos.utils.featurization.text.preprocess run \
  --text-pos 0 \
  --input-preprocessor-folder ./tfidf-model \
  --input-text-path ./input.txt \
  --output-inst-path ./input.tfidf.npz
```

Now, with the input TF-IDF matrix `X` of shape (#input, feat-dim) and label TF-IDF matrix `Z` of shape(#label, feat-dim), we can compute its cosine similarity `P=<X, Z.T>`, and obtain the top-k per row for the `P`,
which can be solved efficiently by this package: https://github.com/ing-bank/sparse_dot_topn.

Hope that resolve your issue. Feel free to reopen if you still have concerns/questions on this subject.
