### ISSUE TITLE
 libpecos_float32 library cannot be found in Colab platform

### ISSUE THREAD

**Issue by LeeTszFung** [amzn/pecos#210]
## Description
When I extract the part of the code of the base.py from the core folder of Pecos and executed it in the colab platform, the exception "libpecos_float32 library cannot be found and built." occurred.

## How to Reproduce?
Running the related python code in colab platform 

### Steps to reproduce
After installing the Pecos package in the colab platform,it shows the path of package is "/usr/local/lib/python3.8/dist-packages".
Then,running all the code of class corelib from base.py and make sure it is successes to execute.
Finally, running the code "clib = corelib(os.path.join(os.path.dirname(os.path.abspath(pecos.__file__)), "core"), "libpecos")" .

(Paste the commands you ran that produced the error.)

1.clib = corelib(os.path.join(os.path.dirname(os.path.abspath(pecos.__file__)), "core"), "libpecos")

## What have you tried to solve it?

1.I tried to convert the libpecos.cpp from core folder to the shared object file.After I converted the libpecos.cpp to libpecos.o file,I failed to convert it to .so file.

## Error message or code output
libpecos_float32 library cannot be found and built

After the pecos package is installed in the colab,I check the folder of pecos package but I cannot find the core folder in the path 
"/usr/local/lib/python3.8/dist-packages". I also printed the path of .so file  which is 
"/usr/local/lib/python3.8/dist-packages/pecos/core/libpecos_float32".As a result,I think the reason for the error is lacking the .so file or the path is wrong. Can you directly provide the .so file to the GitHub? I am willing to directly upload the .so file to the colab platform and use the ctypes.CDLL function to execute the .so file.Thank you

## Environment
- Operating system: linux
- Python version:3.8.10
- PECOS version:0.2.0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by weiliw-amz** [comment]
Thanks for contacting, PECOS does not have version `0.2.0` release available. Please check our tags and release list: https://github.com/amzn/pecos/tags

Please try installing from available versions again. If problem persist, please provide commands and source the PECOS you install from, and we'll be able to help.

**Comment by yangzhao1230** [comment]
Hi, I met the same question:
![image](https://github.com/amzn/pecos/assets/52462696/00e3ee22-7919-4d42-b58d-4916ac8b9884)
