### ISSUE TITLE
ScipyCsrF32 Issue

### ISSUE THREAD

**Issue by mmoradifard** [amzn/pecos#217]
Trying to test the linear model using a sample. The code is as following:

X_trn = np.array([[0.3, 0.5, 0.1],[0.2, 0.1, 0.8]])
Y_trn = np.array([[0.0, 0.0, 0.0, 1.0],[1.0, 0.0, 0.0, 0.0]])

import scipy
scipy.sparse.save_npz('temp_xtrn.npz', sA)
scipy.sparse.save_npz('temp_ytrn.npz', sB)
X = XLinearModel.load_feature_matrix("temp_xtrn.npz")
Y = XLinearModel.load_label_matrix("temp_ytrn.npz", for_training=True)
xlm = XLinearModel.train(X, Y)
 
while running the last line produces the following error:
    517         """
    518         dtype = np.float32
--> 519         assert X.dtype == dtype
    520         assert Y.dtype == dtype
    521         if isinstance(X, (smat.csr_matrix, ScipyCsrF32)):

AssertionError: 

Any ideas how you exactly mean by using Scipy? if the problem is coming from this, how should use Scipy to able to used for this arbitrary example.

Thanks

**Comment by weiliw-amz** [comment]
Hi mmoradifard,

I think the error is that by default Numpy uses float64 for floating point arrays, but PECOS require float32.
Try initialize your input like:
```
X_trn = np.array([[0.3, 0.5, 0.1],[0.2, 0.1, 0.8]], dtype=np.float32)
Y_trn = np.array([[0.0, 0.0, 0.0, 1.0],[1.0, 0.0, 0.0, 0.0]], dtype=np.float32)
```

**Comment by rofuyu** [comment]
Closing this issue.
