### ISSUE TITLE
train model, the process core dump

### ISSUE THREAD

**Issue by runningabcd** [amzn/pecos#228]

**Comment by runningabcd** [comment]
<img width="1301" alt="截屏2023-06-15 21 53 27" src="https://github.com/amzn/pecos/assets/8281035/8bed5eb9-5ede-4827-95b1-ce78dd9f0b1a">

the process core, help

**Comment by jiong-zhang** [comment]
Hi @runningabcd could you provide your hardware/dependency setup and minimal example so we can investigate?

**Comment by runningabcd** [comment]
> Hi @runningabcd could you provide your hardware/dependency setup and minimal example so we can investigate?

hi, Thanks for your reply。
My hardware info:
nvidia/cuda:11.7.0-base-ubuntu22.04
Python 3.10.6
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
<img width="1306" alt="截屏2023-06-16 10 11 48" src="https://github.com/amzn/pecos/assets/8281035/fee546ce-626a-4ae3-9058-2612c946df7e">
<img width="906" alt="截屏2023-06-16 10 13 14" src="https://github.com/amzn/pecos/assets/8281035/fa26ab46-4267-4209-b3e7-92dd610236f1">
<img width="317" alt="截屏2023-06-16 10 13 57" src="https://github.com/amzn/pecos/assets/8281035/d2ddcf21-4a27-4994-8f7c-86793b004dca">





<img width="898" alt="截屏2023-06-16 10 12 54" src="https://github.com/amzn/pecos/assets/8281035/33bf6604-b35e-427e-baa8-5e94cc1ceacf">

**Comment by runningabcd** [comment]
> Hi @runningabcd could you provide your hardware/dependency setup and minimal example so we can investigate?



> Hi @runningabcd could you provide your hardware/dependency setup and minimal example so we can investigate?

example:
https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21/train_and_predict.sh

my test command:

python3 -m pecos.xmc.xtransformer.train --trn-text-path ../xmc-base/wiki10-31k/X.trn.txt --trn-feat-path ../xmc-base/wiki10-31k/tfidf-attnxml/X.trn.npz --trn-label-path ../xmc-base/wiki10-31k/Y.trn.npz --model-dir ../bert-base-uncased/ --params-path ./params/wiki10-31k/bert/params.json

<img width="655" alt="截屏2023-06-16 10 16 40" src="https://github.com/amzn/pecos/assets/8281035/1912657c-d8ed-4944-91f6-b5489e0e3c2f">

**Comment by runningabcd** [comment]
> Hi @runningabcd could you provide your hardware/dependency setup and minimal example so we can investigate?

My english is not very good,can we communicate in chinese?

运行环境是 从nvidia 官网pull 的 docker 镜像，镜像版本：nvidia/cuda:11.7.0-base-ubuntu22.04
python 版本：Python 3.10.6
gcc版本：gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0 

样例是用的
(https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21/train_and_predict.sh)

首先把所需要的文件下载到本地以后，直接通过命令行运行

已下载的文件如下：
<img width="926" alt="截屏2023-06-16 10 27 13" src="https://github.com/amzn/pecos/assets/8281035/d1ef70c9-0de4-47f6-8101-02aaf5f97797">
<img width="1097" alt="截屏2023-06-16 10 28 31" src="https://github.com/amzn/pecos/assets/8281035/b08658a6-0348-4556-8f57-5f426d94b7da">


执行的命令是：
python3 -m pecos.xmc.xtransformer.train --trn-text-path ../xmc-base/wiki10-31k/X.trn.txt --trn-feat-path ../xmc-base/wiki10-31k/tfidf-attnxml/X.trn.npz --trn-label-path ../xmc-base/wiki10-31k/Y.trn.npz --model-dir ../bert-base-uncased/ --params-path ./params/wiki10-31k/bert/params.json

每次执行后，整个进程都会 coredump，每个 core 文件20G 左右，目前通过 string -10 core文件，很难追踪问题

是操作姿势有问题吗？还是系统版本不兼容呢
