### ISSUE TITLE
text example error

### ISSUE THREAD

**Issue by xyan326** [amzn/pecos#23]
tried to run the following code:
"
python3 -m pecos.apps.text2text.train \
  --input-text-path ./training-data.txt \
  --vectorizer-config-path ./config.json\
  --output-item-path ./output-labels.txt \
  --model-folder ./pecos-text2text-model
"

And got error saying No such file or directory: ' ./config,json'

Can you help?

**Comment by OctoberChang** [comment]
Hi xyan326,

Yon need to provide the `./config.json` file which specifies the TFIDF vectorizer configuration. You can find a toy example of such file in this README (https://github.com/amzn/pecos/tree/mainline/pecos/utils/featurization/text). 

Let us know if you encouter other issue.

**Comment by xyan326** [comment]
Thank!
I wonder if there is a consistent code to show a toy example of the text2text?

**Comment by OctoberChang** [comment]
Closing this issue, as we updated the Text2Text README with more details.
