### ISSUE TITLE
XMC - XRTransformer - Recommended way to train on large datasets(200k labels)

### ISSUE THREAD

**Issue by codemonk2023** [amzn/pecos#231]
Hello, 

Is there any recommended way to run XRTransformer on large datasets in terms of AWS machine and environment setup including parameters? I just ran and my python notebook stopped without any logs? Also is there a way to log the errors and warnings?

**Comment by jiong-zhang** [comment]
You can refer to examples [here](https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21) for parameter setups for datasets from 4k to 3m labels (requires p3.16xlarge or better instance).
