### ISSUE TITLE
XMC - XRTransformer - Sequence Length

### ISSUE THREAD

**Issue by codemonk2023** [amzn/pecos#232]
Hello, Am trying to train XRTransformer on documents that are longer than 128 tokens. Are there any hyperparameters to increase or capture longer documents?

**Comment by jiong-zhang** [comment]
You can set the `truncate_length` parameter under `pecos.xmc.xtransformer.matcher.TransformerMatcher.PredParams` to the value that fits your data. [example](https://github.com/amzn/pecos/blob/mainline/examples/xr-transformer-neurips21/params/wiki10-31k/bert/params.json#L239)
