### ISSUE TITLE
Using external Label embeddings (Z matrix) for DistClutering in XLinear model

### ISSUE THREAD

**Issue by subsid** [amzn/pecos#233]
Hello,

We are trying to leverage XR-Linear distributed for a large dataset (100s millions of labels). I noticed that the current setup does not support adding label-embeddings for the distributed clustering step. 

It is restricted to PIFA and PII aggregation ([Assert](https://github.com/amzn/pecos/blob/037312faa219ff8af25f10cd93843fb3e2790af0/pecos/distributed/xmc/base.py#L301), [LabelFactory call without Z](https://github.com/amzn/pecos/blob/037312faa219ff8af25f10cd93843fb3e2790af0/pecos/distributed/xmc/base.py#L360)).

Curious, is there a conceptual reason for not supporting methods like `lf_concat` or `convext_combine` with label features?

Thank you! (Love your papers and this project!)

**Comment by jiong-zhang** [comment]
The distributed training currently does not support user supplied label features. A practical reason is that for distributed problems with large number of labels, matrix `Z` usually costs much larger memory than either `X` or `Y`. The master node needs to hold the full `Z` matrix during meta-tree clustering, which is usually a memory bottleneck. 

Adding user supplied feature matrix will greatly increase the chance for master node to be OOM, therefore we only support PIFA or PII as label features. In the extreme case where even PIFA cannot be held in master memory, we allow user to use `PII` for meta-tree clustering and `PIFA` for sub-tree clustering. In practice we observe little performance drop by such substitute.

**Comment by subsid** [comment]
Thanks @jiong-zhang. That makes sense. 

In our case, the issue is around data staleness (not memory, we are able to load Z on a large machine). Our dataset takes ~3 days to train on a single large node. So I was exploring the distributed setting to make this faster. 

Given what you've mentioned, I think I'll try modifying the implementation to allow label features and see how things look (and report back!). 

Thank you!
