### ISSUE TITLE
Validation set split

### ISSUE THREAD

**Issue by theejung** [amzn/pecos#24]
Hi,

I am just trying to replicate the benchmark result for Wiki10-31K using xtransformer and xlinear. 
I wonder if there is internal step to split train set to validation set. Otherwise, should i pre-process to generate held-out validation set before train it?

Thanks!

**Comment by jiong-zhang** [comment]
Hi THEEJUNG,

Thanks for your interest. As of now (v0.1.0) there is no built-in step to split input dataset. You need to split your dataset before feeding into PECOS.

**Comment by theejung** [comment]
Thanks for letting me know! I'll close this issue.
