### ISSUE TITLE
Issue with --label-embed-type pifa_lf_concat::Z=${Z_pifa_file}

### ISSUE THREAD

**Issue by zusmani** [amzn/pecos#50]
## Description
I am trying to use ----label-embed-type parameter in the training and it produces this error.
``` ValueError: Object arrays cannot be loaded when allow_pickle=False ``` - Coming from np.load() function. 

I have tested loading of NPZ file for z_labels (compressed and uncompressed, both) it produces this error if allow_pickle=False
I have load data by defining the allow_pickle=True for np.load() function. 

Can you please add description of this file format or can we sent this parameter as an input? 

This is the data I have after loading npz file with allow_pickle = True

```
[array(['Trump', 'Bus', 'Trolly '], dtype='<U23')
 array(['Show', 'Disp'], dtype='<U20')
 array(['Recap rew'], dtype='<U24')
 array(['Core, '], dtype='<U32')
 array(['Hoe'], dtype='<U10')
 array(['Plan'], dtype='<U21')]
```

## How to Reproduce?
Execute model training with numpy version  1.21.2

```python
python -m pecos.apps.text2text.train \
  --label-embed-type pifa_lf_concat::Z=${Z_pifa_file} \
  -i ${train_file} \ 
  -m ${model_folder}
```

## Error message or code output
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/pecos_git/pecos/pecos/apps/text2text/train.py", line 311, in <module>
    train(args)
  File "/home/jupyter/pecos_git/pecos/pecos/apps/text2text/train.py", line 302, in train
    workspace_folder=args.workspace_folder,
  File "/home/jupyter/pecos_git/pecos/pecos/apps/text2text/model.py", line 325, in train
    Z = smat_util.load_matrix(val)
  File "/home/jupyter/pecos_git/pecos/pecos/utils/smat_util.py", line 117, in load_matrix
    mat = np.load(src)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 441, in load
    pickle_kwargs=pickle_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/format.py", line 743, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

## Environment
- Operating system: Unix Ubuntu (on GCP)
- Python version: 3.8
- PECOS version: 0.1.0
- numpy version: 1.21.2

**Comment by OctoberChang** [comment]
Hi @zusmani ,

Thanks for your interest in PECOS!

For the usage of `--label-embed-type pifa_lf_concat::Z=${Z_pifa_file}`,
the Z_pifa_file should be a `.npz` or `.npy` file storing the label embedding matrix of shape `[L,d]`, 
where `L` is the number of labels and `d` is the dimension of label embedding. 

Please let me knwo if this address your issue, thanks.

**Comment by zusmani** [comment]
Hello @OctoberChang 

Thank you for getting back to me.
I am performing following step to create npz file
``` np.savez_compressed(z_file_name, L=z_lbl_count, d=z_lbl_str)```
where z_lbl_count contains count of labels in the embedding.
e.g. [2, 1, 3]
z_lbl_str contain label embeddings i.e. 
[ss, xx]
[zzz]
[qq, pp, oo]

It still shows the same error, if I try np.load file without providing this parameter allow_pickle=True.

**Comment by zusmani** [comment]
Hey @OctoberChang 

I have explored Z.pifa.npz file, available in the test folder and it contains different attributes as described above. 
Please let me know how can I make best use of ``` -- label-embed-type``` parameter?

![image](https://user-images.githubusercontent.com/7218916/132994779-39a2d3f3-dcce-4f60-a009-3ba6e7319ff8.png)

**Comment by OctoberChang** [comment]
@zusmani ,

The `Z.pifa.npz` contains the [scipy sparse csr matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html). You should load it via
``` python
import pecos.utils as smat_util
Z = smat_util.load_matrix('Z.pifa.npz').astype(np.float32)

# you should see type(Z)=scipy.sparse.csr_matrix
print(type(Z))
````

Going back to the usage of `--label-embed-type` in `text2text`:
(1) If you do not have an explicit label embeddings, you can just use pifa as label embeddings
``` python 
python -m pecos.apps.text2text.train \
  --label-embed-type pifa \
  -i ${train_file} \ 
  -m ${model_folder}
```
(2) If you want to use pifa label embeddings concatnate with an explicit label embeddings (`np.array` or `scipy.sparse.csr_matrix`) saved in the `Z_pifa_file`, 
``` python 
python -m pecos.apps.text2text.train \
  --label-embed-type pifa_lf_concat::Z=${Z_pifa_file} \
  -i ${train_file} \ 
  -m ${model_folder}
```

**Comment by zusmani** [comment]
Hi @OctoberChang  

I have explicit label embeddings and need to transform into the required format.
It would be ideal if you provide feature/function which takes string type labels embedding text file (like text2text model) and transform into the required format and parse to model computation,. 

I am working around it and it is time consuming to understand the relevant pecos code modules/functions and input format etc. 
I have label embeddings as a separate text file, index-wise mapping to train text file. Each line contains at least one or multiple labels. Can you please explain how to transform into required Z_pifa_file format?

**Comment by OctoberChang** [comment]
Closing this issue. Feel free to re-open if you still can not have any qustion.
