### ISSUE TITLE
Are PECOS models serializable? 

### ISSUE THREAD

**Issue by ayshtmr** [amzn/pecos#99]
Does PECOS support serializing models to one of the popular serialization formats like ONNX?

**Comment by rofuyu** [comment]
PECOS models have our own serialization. It does not yet support the ONNX serialization.

**Comment by OctoberChang** [comment]
closing this issue as there are no additional follow-up.

**Comment by juhoinkinen** [comment]
> PECOS models have our own serialization. It does not yet support the ONNX serialization.

I guess PECOS still does not support ONNX? Only this issue references it in this repository.

We would like to avoid increasing the size of our Docker image too much (https://github.com/NatLibFi/Annif/pull/798#issuecomment-2376115075), is there any advice for this BTW?
